version: '3.4'

services:
  employeesaiohttp:
    image: employeesaiohttp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: >
      bash -c "python3 init_db.py &&
      python3 employees/main.py"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    env_file:
      - .env
